version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: myappge-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: myappge
      POSTGRES_USER: myappge
      POSTGRES_PASSWORD: myappge123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: myappge-api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  pgdata:
